import type { Task, Priority, IssueType, Status, Label } from './types';

const labels: Label[] = [
    { id: '1', name: 'Frontend', color: 'bg-blue-500' },
    { id: '2', name: 'Backend', color: 'bg-green-500' },
    { id: '3', name: 'Design', color: 'bg-purple-500' },
    { id: '4', name: 'Urgent', color: 'bg-red-500' },
    { id: '5', name: 'Feature', color: 'bg-yellow-500' },
];

export const initialTasks: Task[] = [
    {
        id: 'task-1',
        title: 'Implement user authentication',
        description: 'Create login and signup functionality with JWT tokens',
        status: 'todo' as Status,
        priority: 'high' as Priority,
        type: 'story' as IssueType,
        assignee: 'John Doe',
        reporter: 'Jane Smith',
        labels: [labels[0], labels[1]],
        comments: [],
        createdAt: new Date('2026-01-15'),
        updatedAt: new Date('2026-01-15'),
        estimate: 8,
        timeSpent: 0,
        dueDate: new Date('2026-01-25'),
    },
    {
        id: 'task-2',
        title: 'Fix responsive layout issues',
        description: 'Mobile view is broken on iPhone devices',
        status: 'todo' as Status,
        priority: 'highest' as Priority,
        type: 'bug' as IssueType,
        assignee: 'Sarah Johnson',
        reporter: 'John Doe',
        labels: [labels[0], labels[3]],
        comments: [
            {
                id: 'c1',
                author: 'John Doe',
                content: 'This needs to be fixed ASAP',
                timestamp: new Date('2026-01-16'),
            },
        ],
        createdAt: new Date('2026-01-16'),
        updatedAt: new Date('2026-01-17'),
        estimate: 4,
        timeSpent: 1,
    },
    {
        id: 'task-3',
        title: 'Design new dashboard wireframes',
        description: 'Create modern dashboard design with analytics widgets',
        status: 'in-progress' as Status,
        priority: 'medium' as Priority,
        type: 'task' as IssueType,
        assignee: 'Mike Chen',
        reporter: 'Jane Smith',
        labels: [labels[2]],
        comments: [],
        createdAt: new Date('2026-01-10'),
        updatedAt: new Date('2026-01-18'),
        estimate: 6,
        timeSpent: 3,
        dueDate: new Date('2026-01-22'),
    },
    {
        id: 'task-4',
        title: 'Optimize database queries',
        description: 'Improve performance of user dashboard queries by adding proper indexes',
        status: 'in-progress' as Status,
        priority: 'high' as Priority,
        type: 'task' as IssueType,
        assignee: 'Alex Wong',
        reporter: 'Sarah Johnson',
        labels: [labels[1]],
        comments: [
            {
                id: 'c2',
                author: 'Alex Wong',
                content: 'Identified slow queries, working on optimization',
                timestamp: new Date('2026-01-17'),
            },
        ],
        createdAt: new Date('2026-01-12'),
        updatedAt: new Date('2026-01-18'),
        estimate: 5,
        timeSpent: 2,
    },
    {
        id: 'task-5',
        title: 'Code review for payment module',
        description: 'Review and approve pull request #234 for payment integration',
        status: 'in-review' as Status,
        priority: 'high' as Priority,
        type: 'task' as IssueType,
        assignee: 'John Doe',
        reporter: 'Mike Chen',
        labels: [labels[1], labels[4]],
        comments: [],
        createdAt: new Date('2026-01-14'),
        updatedAt: new Date('2026-01-18'),
        estimate: 3,
        timeSpent: 1,
    },
    {
        id: 'task-6',
        title: 'Update API documentation',
        description: 'Document all new endpoints added in v2.0',
        status: 'done' as Status,
        priority: 'low' as Priority,
        type: 'task' as IssueType,
        assignee: 'Sarah Johnson',
        reporter: 'Jane Smith',
        labels: [labels[1]],
        comments: [
            {
                id: 'c3',
                author: 'Jane Smith',
                content: 'Great work! Documentation looks comprehensive.',
                timestamp: new Date('2026-01-17'),
            },
        ],
        createdAt: new Date('2026-01-08'),
        updatedAt: new Date('2026-01-17'),
        estimate: 4,
        timeSpent: 4,
    },
    {
        id: 'task-7',
        title: 'Setup CI/CD pipeline',
        description: 'Configure automated testing and deployment workflows',
        status: 'done' as Status,
        priority: 'medium' as Priority,
        type: 'story' as IssueType,
        assignee: 'Alex Wong',
        reporter: 'John Doe',
        labels: [labels[1]],
        comments: [],
        createdAt: new Date('2026-01-05'),
        updatedAt: new Date('2026-01-16'),
        estimate: 8,
        timeSpent: 7,
    },
];

export const availableLabels = labels;
